using System.ComponentModel;

namespace BlazorTabler;

public enum TablerColors
{
    [Description("")] None,
    [Description("bg-primary")] Primary,
    [Description("bg-secondary")] Secondary,
    [Description("bg-success")] Success,
    [Description("bg-info")] Info,
    [Description("bg-warning")] Warning,
    [Description("bg-danger")] Danger,
    [Description("bg-light")] Light,
    [Description("bg-dark")] Dark,
    [Description("bg-muted")] Muted,
    [Description("bg-blue")] Blue,
    [Description("bg-azure")] Azure,
    [Description("bg-indigo")] Indigo,
    [Description("bg-purple")] Purple,
    [Description("bg-pink")] Pink,
    [Description("bg-red")] Red,
    [Description("bg-orange")] Orange,
    [Description("bg-yellow")] Yellow,
    [Description("bg-lime")] Lime,
    [Description("bg-green")] Green,
    [Description("bg-teal")] Teal,
    [Description("bg-cyan")] Cyan,
    [Description("bg-facebook")] Facebook,
    [Description("bg-twitter")] Twitter,
    [Description("bg-linkedin")] LinkedIn,
    [Description("bg-google")] Google,
    [Description("bg-youtube")] YouTube,
    [Description("bg-vimeo")] Vimeo,
    [Description("bg-dribbble")] Dribbble,
    [Description("bg-github")] GitHub,
    [Description("bg-instagram")] Instagram,
    [Description("bg-pinterest")] Pinterest,
    [Description("bg-vk")] Vk,
    [Description("bg-rss")] Rss,
    [Description("bg-flickr")] Flickr,
    [Description("bg-bitbucket")] Bitbucket,
    [Description("bg-tabler")] Tabler,
    [Description("bg-black")] Black,
    [Description("bg-white")] White,
    [Description("bg-body")] Body,
    [Description("bg-transparent")] Transparent,
    [Description("bg-body-secondary")] BodySecondary,
    [Description("bg-body-tertiary")] BodyTertiary,
    [Description("bg-primary-subtle")] PrimarySubtle,
    [Description("bg-secondary-subtle")] SecondarySubtle,
    [Description("bg-success-subtle")] SuccessSubtle,
    [Description("bg-info-subtle")] InfoSubtle,
    [Description("bg-warning-subtle")] WarningSubtle,
    [Description("bg-danger-subtle")] DangerSubtle,
    [Description("bg-light-subtle")] LightSubtle,
    [Description("bg-dark-subtle")] DarkSubtle,
    [Description("bg-gradient")] Gradient,
    [Description("bg-gray-50")] Gray50,
    [Description("bg-gray-100")] Gray100,
    [Description("bg-gray-200")] Gray200,
    [Description("bg-gray-300")] Gray300,
    [Description("bg-gray-400")] Gray400,
    [Description("bg-gray-500")] Gray500,
    [Description("bg-gray-600")] Gray600,
    [Description("bg-gray-700")] Gray700,
    [Description("bg-gray-800")] Gray800,
    [Description("bg-gray-900")] Gray900
    
}
 

public enum TablerColorsLight
{
    [Description("bg-primary-lt")] Primary,
    [Description("bg-secondary-lt")] Secondary,
    [Description("bg-success-lt")] Success,
    [Description("bg-info-lt")] Info,
    [Description("bg-warning-lt")] Warning,
    [Description("bg-danger-lt")] Danger,
    [Description("bg-light-lt")] Light,
    [Description("bg-dark-lt")] Dark,
    [Description("bg-muted-lt")] Muted,
    [Description("bg-blue-lt")] Blue,
    [Description("bg-azure-lt")] Azure,
    [Description("bg-indigo-lt")] Indigo,
    [Description("bg-purple-lt")] Purple,
    [Description("bg-pink-lt")] Pink,
    [Description("bg-red-lt")] Red,
    [Description("bg-orange-lt")] Orange,
    [Description("bg-yellow-lt")] Yellow,
    [Description("bg-lime-lt")] Lime,
    [Description("bg-green-lt")] Green,
    [Description("bg-teal-lt")] Teal,
    [Description("bg-cyan-lt")] Cyan,
    [Description("bg-facebook-lt")] Facebook,
    [Description("bg-twitter-lt")] Twitter,
    [Description("bg-linkedin-lt")] LinkedIn,
    [Description("bg-google-lt")] Google,
    [Description("bg-youtube-lt")] YouTube,
    [Description("bg-vimeo-lt")] Vimeo,
    [Description("bg-dribbble-lt")] Dribbble,
    [Description("bg-github-lt")] GitHub,
    [Description("bg-instagram-lt")] Instagram,
    [Description("bg-pinterest-lt")] Pinterest,
    [Description("bg-vk-lt")] VK,
    [Description("bg-rss-lt")] RSS,
    [Description("bg-flickr-lt")] Flickr,
    [Description("bg-bitbucket-lt")] Bitbucket,
    [Description("bg-tabler-lt")] Tabler,
    [Description("bg-white-lt")] White
}
 
