using System.ComponentModel;

namespace BlazorTabler;

public enum TablerColors
{
    [Description("bg-primary-lt")] PrimaryLt,
    [Description("bg-primary")] Primary,
    [Description("bg-secondary-lt")] SecondaryLt,
    [Description("bg-secondary")] Secondary,
    [Description("bg-success-lt")] SuccessLt,
    [Description("bg-success")] Success,
    [Description("bg-info-lt")] InfoLt,
    [Description("bg-info")] Info,
    [Description("bg-warning-lt")] WarningLt,
    [Description("bg-warning")] Warning,
    [Description("bg-danger-lt")] DangerLt,
    [Description("bg-danger")] Danger,
    [Description("bg-light-lt")] LightLt,
    [Description("bg-light")] Light,
    [Description("bg-dark-lt")] DarkLt,
    [Description("bg-dark")] Dark,
    [Description("bg-muted-lt")] MutedLt,
    [Description("bg-muted")] Muted,
    [Description("bg-blue-lt")] BlueLt,
    [Description("bg-blue")] Blue,
    [Description("bg-azure-lt")] AzureLt,
    [Description("bg-azure")] Azure,
    [Description("bg-indigo-lt")] IndigoLt,
    [Description("bg-indigo")] Indigo,
    [Description("bg-purple-lt")] PurpleLt,
    [Description("bg-purple")] Purple,
    [Description("bg-pink-lt")] PinkLt,
    [Description("bg-pink")] Pink,
    [Description("bg-red-lt")] RedLt,
    [Description("bg-red")] Red,
    [Description("bg-orange-lt")] OrangeLt,
    [Description("bg-orange")] Orange,
    [Description("bg-yellow-lt")] YellowLt,
    [Description("bg-yellow")] Yellow,
    [Description("bg-lime-lt")] LimeLt,
    [Description("bg-lime")] Lime,
    [Description("bg-green-lt")] GreenLt,
    [Description("bg-green")] Green,
    [Description("bg-teal-lt")] TealLt,
    [Description("bg-teal")] Teal,
    [Description("bg-cyan-lt")] CyanLt,
    [Description("bg-cyan")] Cyan,
    [Description("bg-black-lt")] BlackLt,
    [Description("bg-black")] Black,
    [Description("bg-white-lt")] WhiteLt,
    [Description("bg-white")] White,
}