using System.ComponentModel;

namespace BlazorTabler;

public enum TablerTextColors
{
  [Description("text-primary")] Primary,
  [Description("text-secondary")] Secondary,
  [Description("text-success")] Success,
  [Description("text-info")] Info,
  [Description("text-warning")] Warning,
  [Description("text-danger")] Danger,
  [Description("text-light")] Light,
  [Description("text-dark")] Dark,
  [Description("text-muted")] Muted,
  [Description("text-blue")] Blue,
  [Description("text-azure")] Azure,
  [Description("text-indigo")] Indigo,
  [Description("text-purple")] Purple,
  [Description("text-pink")] Pink,
  [Description("text-red")] Red,
  [Description("text-orange")] Orange,
  [Description("text-yellow")] Yellow,
  [Description("text-lime")] Lime,
  [Description("text-green")] Green,
  [Description("text-teal")] Teal,
  [Description("text-cyan")] Cyan,
  [Description("text-facebook")] Facebook,
  [Description("text-twitter")] Twitter,
  [Description("text-linkedin")] LinkedIn,
  [Description("text-google")] Google,
  [Description("text-youtube")] YouTube,
  [Description("text-vimeo")] Vimeo,
  [Description("text-dribbble")] Dribbble,
  [Description("text-github")] GitHub,
  [Description("text-instagram")] Instagram,
  [Description("text-pinterest")] Pinterest,
  [Description("text-vk")] VK,
  [Description("text-rss")] RSS,
  [Description("text-flickr")] Flickr,
  [Description("text-bitbucket")] Bitbucket,
  [Description("text-tabler")] Tabler,
  [Description("text-black")] Black,
  [Description("text-white")] White,
  [Description("text-body")] Body,
  [Description("text-black-50")] Black50,
  [Description("text-white-50")] White50,
  [Description("text-body-secondary")] BodySecondary,
  [Description("text-body-tertiary")] BodyTertiary,
  [Description("text-body-emphasis")] BodyEmphasis,
  [Description("text-primary-emphasis")] PrimaryEmphasis,
  [Description("text-secondary-emphasis")] SecondaryEmphasis,
  [Description("text-success-emphasis")] SuccessEmphasis,
  [Description("text-info-emphasis")] InfoEmphasis,
  [Description("text-warning-emphasis")] WarningEmphasis,
  [Description("text-danger-emphasis")] DangerEmphasis,
  [Description("text-light-emphasis")] LightEmphasis,
  [Description("text-dark-emphasis")] DarkEmphasis
   
}


public enum TablerTextBackgroundColors
{
  [Description("text-bg-primary")] Primary,
  [Description("text-bg-secondary")] Secondary,
  [Description("text-bg-success")] Success,
  [Description("text-bg-info")] Info,
  [Description("text-bg-warning")] Warning,
  [Description("text-bg-danger")] Danger,
  [Description("text-bg-light")] Light,
  [Description("text-bg-dark")] Dark,
  [Description("text-bg-muted")] Muted,
  [Description("text-bg-blue")] Blue,
  [Description("text-bg-azure")] Azure,
  [Description("text-bg-indigo")] Indigo,
  [Description("text-bg-purple")] Purple,
  [Description("text-bg-pink")] Pink,
  [Description("text-bg-red")] Red,
  [Description("text-bg-orange")] Orange,
  [Description("text-bg-yellow")] Yellow,
  [Description("text-bg-lime")] Lime,
  [Description("text-bg-green")] Green,
  [Description("text-bg-teal")] Teal,
  [Description("text-bg-cyan")] Cyan,
  [Description("text-bg-facebook")] Facebook,
  [Description("text-bg-twitter")] Twitter,
  [Description("text-bg-linkedin")] LinkedIn,
  [Description("text-bg-google")] Google,
  [Description("text-bg-youtube")] YouTube,
  [Description("text-bg-vimeo")] Vimeo,
  [Description("text-bg-dribbble")] Dribbble,
  [Description("text-bg-github")] GitHub,
  [Description("text-bg-instagram")] Instagram,
  [Description("text-bg-pinterest")] Pinterest,
  [Description("text-bg-vk")] VK,
  [Description("text-bg-rss")] RSS,
  [Description("text-bg-flickr")] Flickr,
  [Description("text-bg-bitbucket")] Bitbucket,
  [Description("text-bg-tabler")] Tabler
   
}



public enum TablerTextForegroundColors
{
    [Description("text-primary-fg")] Primary,
    [Description("text-secondary-fg")] Secondary,
    [Description("text-success-fg")] Success,
    [Description("text-info-fg")] Info,
    [Description("text-warning-fg")] Warning,
    [Description("text-danger-fg")] Danger,
    [Description("text-light-fg")] Light,
    [Description("text-dark-fg")] Dark,
    [Description("text-muted-fg")] Muted,
    [Description("text-blue-fg")] Blue,
    [Description("text-azure-fg")] Azure,
    [Description("text-indigo-fg")] Indigo,
    [Description("text-purple-fg")] Purple,
    [Description("text-pink-fg")] Pink,
    [Description("text-red-fg")] Red,
    [Description("text-orange-fg")] Orange,
    [Description("text-yellow-fg")] Yellow,
    [Description("text-lime-fg")] Lime,
    [Description("text-green-fg")] Green,
    [Description("text-teal-fg")] Teal,
    [Description("text-cyan-fg")] Cyan,
    [Description("text-facebook-fg")] Facebook,
    [Description("text-twitter-fg")] Twitter,
    [Description("text-linkedin-fg")] LinkedIn,
    [Description("text-google-fg")] Google,
    [Description("text-youtube-fg")] YouTube,
    [Description("text-vimeo-fg")] Vimeo,
    [Description("text-dribbble-fg")] Dribbble,
    [Description("text-github-fg")] GitHub,
    [Description("text-instagram-fg")] Instagram,
    [Description("text-pinterest-fg")] Pinterest,
    [Description("text-vk-fg")] VK,
    [Description("text-rss-fg")] RSS,
    [Description("text-flickr-fg")] Flickr,
    [Description("text-bitbucket-fg")] Bitbucket,
    [Description("text-tabler-fg")] Tabler,
    [Description("text-gray-50-fg")] Gray50,
    [Description("text-gray-100-fg")] Gray100,
    [Description("text-gray-200-fg")] Gray200,
    [Description("text-gray-300-fg")] Gray300,
    [Description("text-gray-400-fg")] Gray400,
    [Description("text-gray-500-fg")] Gray500,
    [Description("text-gray-600-fg")] Gray600,
    [Description("text-gray-700-fg")] Gray700,
    [Description("text-gray-800-fg")] Gray800,
    [Description("text-gray-900-fg")] Gray900
}
  
    
        
